# SPDX-FileCopyrightText: 2026 Zhengyi Zhang
# SPDX-License-Identifier: GPL-3.0-only

[package]
name = "opto-runtime"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
opto-core.workspace = true
thiserror.workspace = true
rayon.workspace = true
serde.workspace = true
