// SPDX-FileCopyrightText: 2026 Zhengyi Zhang
// SPDX-License-Identifier: GPL-3.0-only

//! Typed Tcl command argument contracts generated by `TclCommand`.

use crate::command_catalog::ParsedInvocation;
use crate::tcl::TclArg;
use std::path::PathBuf;

/// One declaration-driven Tcl argument structure.
pub(crate) trait TclArgs<'a>: Sized {
    /// Materializes typed fields from a schema-validated invocation.
    fn from_invocation(
        command: &str,
        invocation: &ParsedInvocation<'a>,
    ) -> Result<Self, crate::ShellError>;
}

/// One named option occurrence in original invocation order.
///
/// This is used when aliases have distinct semantics or when the order of
/// repeated options (for example SDC path points) is itself meaningful.
pub(crate) struct TclOption<'a> {
    name: &'static str,
    value: TclArg<'a>,
}

impl<'a> TclOption<'a> {
    pub(crate) fn new(name: &'static str, value: TclArg<'a>) -> Self {
        Self { name, value }
    }

    pub(crate) fn name(&self) -> &'static str {
        self.name
    }

    pub(crate) fn value(&self) -> TclArg<'a> {
        self.value
    }
}

/// Conversion from one Tcl object-backed argument into a typed field.
///
/// The raw [`TclArg`] implementation preserves Tcl object identity for
/// collections and lists. Owned scalar implementations are intended for values
/// whose Tcl representation no longer matters after command parsing.
pub(crate) trait FromTclValue<'a>: Sized {
    fn from_tcl_value(
        command: &str,
        argument: &str,
        value: TclArg<'a>,
    ) -> Result<Self, crate::ShellError>;
}

impl<'a> FromTclValue<'a> for TclArg<'a> {
    fn from_tcl_value(
        _command: &str,
        _argument: &str,
        value: TclArg<'a>,
    ) -> Result<Self, crate::ShellError> {
        Ok(value)
    }
}

impl FromTclValue<'_> for String {
    fn from_tcl_value(
        _command: &str,
        _argument: &str,
        value: TclArg<'_>,
    ) -> Result<Self, crate::ShellError> {
        Ok(value.to_string())
    }
}

impl FromTclValue<'_> for PathBuf {
    fn from_tcl_value(
        _command: &str,
        _argument: &str,
        value: TclArg<'_>,
    ) -> Result<Self, crate::ShellError> {
        Ok(Self::from(value.as_str()))
    }
}

macro_rules! numeric_value {
    ($type:ty) => {
        impl FromTclValue<'_> for $type {
            fn from_tcl_value(
                command: &str,
                argument: &str,
                value: TclArg<'_>,
            ) -> Result<Self, crate::ShellError> {
                value.parse::<Self>().map_err(|_| {
                    crate::ShellError::parse(format!(
                        "{command}: invalid value '{value}' for {argument}"
                    ))
                })
            }
        }
    };
}

numeric_value!(f64);
numeric_value!(i32);
numeric_value!(u32);
numeric_value!(usize);
