# SPDX-FileCopyrightText: 2026 Zhengyi Zhang
# SPDX-License-Identifier: GPL-3.0-only

[package]
name = "opto-archive"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
rkyv.workspace = true
serde.workspace = true
