// SPDX-FileCopyrightText: 2026 Zhengyi Zhang
// SPDX-License-Identifier: GPL-3.0-only

//! Technology-mapping mechanics and deterministic artifact materialization.
//!
//! This domain owns target catalogs, cover selection, sequential mapping, and
//! regional commit. Epoch scheduling and timing feedback belong to the engine.

use crate::SynthesisOptions;
use opto_ir::word;

mod architecture;
mod cell;
pub(crate) mod clock_gating;
pub(crate) mod cover;
pub(crate) mod library;
pub(crate) mod logic_partition;
pub(crate) mod materialize;
mod prepare;
mod region_binding;
mod roots;
mod sequential;
pub(crate) mod word_util;

pub use clock_gating::ClockGatingStyle;

pub(crate) use architecture::{
    ArchitectureMappingConfig, RegionalArchitectureRequest, extend_operation_regions_for_memories,
    prepare_regional_architectures,
};
pub(crate) use cell::{MappedCell, MappedInputConnection, MappedOutputConnection};
use library::CombinationalCellCatalog;
pub(crate) use materialize::MappedOutput;
#[cfg(test)]
pub(crate) use materialize::build_test_substrate;
pub(crate) use region_binding::{
    CandidateBindingInputs, RegionPlanBinding, build_candidate_binding,
};
pub(crate) use roots::FullDomainRootSemantics;
use sequential::SequentialCellCatalog;

pub(crate) enum RegionalMappingSeed {
    Private {
        plans: Box<[crate::RegionCoverPlan]>,
        bindings: Box<[RegionPlanBinding]>,
    },
}

impl RegionalMappingSeed {
    pub(crate) fn bindings(&self) -> &[RegionPlanBinding] {
        let Self::Private { bindings, .. } = self;
        bindings
    }

    pub(crate) fn bindings_mut(&mut self) -> &mut [RegionPlanBinding] {
        let Self::Private { bindings, .. } = self;
        bindings
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct TargetMappingContextKey([u8; 32]);

impl TargetMappingContextKey {
    pub(crate) fn from_options(options: &SynthesisOptions) -> Self {
        Self(options.target_cells.content_fingerprint().bytes())
    }

    #[cfg(test)]
    pub(crate) const fn bytes(self) -> [u8; 32] {
        self.0
    }
}

#[derive(Debug)]
pub(crate) struct TargetMappingContext {
    pub(crate) combinational_catalog: CombinationalCellCatalog,
    sequential_catalog: SequentialCellCatalog,
    clock_gating_catalog: clock_gating::ClockGatingCatalog,
    pub(crate) config: crate::SynthesisConfig,
}

impl TargetMappingContext {
    pub(crate) fn new(options: &SynthesisOptions, config: crate::SynthesisConfig) -> Self {
        Self {
            combinational_catalog: CombinationalCellCatalog::new(options, config.diagnostics),
            sequential_catalog: SequentialCellCatalog::new(options),
            clock_gating_catalog: clock_gating::ClockGatingCatalog::new(options),
            config,
        }
    }

    pub(crate) fn publish_owned_preparation(
        &self,
        module: &mut word::WordModule,
        clock_gating: Option<ClockGatingStyle>,
        target_mapping: bool,
        ownership: &mut crate::regional::StructuralOwnershipProvenance,
    ) -> Result<(), crate::SynthError> {
        prepare::prepare_private_region(prepare::PrivateRegionPreparation {
            module,
            sequential_catalog: &self.sequential_catalog,
            clock_gating,
            clock_gating_catalog: &self.clock_gating_catalog,
            target_mapping,
            timing_diagnostics: self.config.diagnostics.timing,
            ownership,
        })
    }
}

pub(crate) struct MappingConfig<'a> {
    pub(crate) options: &'a SynthesisOptions,
    pub(crate) port_bindings: &'a opto_timing::PortBindings,
    pub(crate) mapping_context: &'a TargetMappingContext,
    pub(crate) scenarios: &'a opto_timing::ScenarioSet,
    pub(crate) object_bindings: std::sync::Arc<opto_timing::TimingObjectBindings>,
    pub(crate) effort: crate::SynthesisEffort,
    pub(crate) design_id: opto_timing::DesignId,
    pub(crate) design_references: &'a std::collections::BTreeSet<String>,
    pub(crate) reference_ports: &'a crate::ReferencePortMap,
    pub(crate) source_instances: &'a crate::artifact::provenance::SourceInstanceProvenance,
    pub(crate) base_revision: opto_ir::RevisionId,
    pub(crate) power_evaluator: &'a dyn crate::SynthesisPowerEvaluator,
}

/// Whether a mapped cell name was generated by region materialization.
pub(crate) fn is_synthetic_region_cell_name(name: &str) -> bool {
    name.starts_with(materialize::REGION_CELL_PREFIX)
}

/// Whether a mapped net name was generated by materialization.
pub(crate) fn is_synthetic_net_name(name: &str) -> bool {
    name.starts_with(materialize::MAPPED_NET_PREFIX)
}
