# SPDX-FileCopyrightText: 2026 Zhengyi Zhang
# SPDX-License-Identifier: GPL-3.0-only

format = 1
name = "upstream-ibex"
cases = [
  "qualification/upstream/ibex-alu/case.toml",
  "qualification/upstream/ibex-core/case.toml",
]
